{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-backup-config
  namespace: chatbot
data:
  config.yml: |
    general:
      remote_storage: gcs
      disable_progress_bar: true
    clickhouse:
      username: "{{ .Values.clickhouse.auth.username }}"
      password: "{{ .Values.clickhouse.auth.password }}"
      host: "localhost"
      port: "9000"
      cluster_name: "default" 
      cluster_username: "{{ .Values.clickhouse.auth.username }}"
      cluster_password: "{{ .Values.clickhouse.auth.password }}"
      freeze_by_part: true
      skip_tables:
        - system.*
        - default.blob_storage_file_log

    gcs:
      bucket: {{ .Values.backup.gcsBucket }}
      path: {{ .Values.backup.gcsPath }}
      credentials_file: "/etc/clickhouse-backup/{{ .Values.backup.gcsKeyFile }}"
{{- end }}
