{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-backup-config
  namespace: chatbot
data:
  config.yml: |
    general:
      remote_storage: gcs
      disable_progress_bar: true
    clickhouse:
      username: "$CLICKHOUSE_USER"
      password: "$CLICKHOUSE_PASSWORD"
      host: "$CLICKHOUSE_HOST"
      port: $CLICKHOUSE_PORT
    gcs:
      bucket: {{ .Values.backup.gcsBucket }}
      path: {{ .Values.backup.gcsPath }}
      credentials_file: "/etc/clickhouse-backup/{{ .Values.backup.gcsKeyFile }}"
{{- end }}
