{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-gcs-config
  namespace: chatbot
data:
  storage-gcs.xml: |
    <clickhouse>
      <storage_configuration>
        <disks>
          <backups>
            <type>s3</type>
            <allowed_disk>backups</allowed_disk>
            <endpoint>https://storage.googleapis.com/{{ .Values.backup.gcsBucket }}/{{ .Values.backup.gcsPath }}/</endpoint>
            <access_key_id from_env="ACCESS_KEY_ID"/>
            <secret_access_key from_env="SECRET_ACCESS_KEY"/>
            <support_batch_delete>false</support_batch_delete>
            <metadata_path>/var/lib/clickhouse/disks/backups/</metadata_path>
          </backups>
        </disks>
        <policies>
          <backups_policy>
            <volumes>
              <main>
                <disk>backups</disk>
              </main>
            </volumes>
          </backups_policy>
        </policies>
      </storage_configuration>
    </clickhouse>
{{- end }}
