{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-gcs-config
  namespace: chatbot
data:
  storage-gcs.xml: |
    <clickhouse>
      <storage_configuration>
        <disks>
          <backups>
            <type>s3_plain</type>
            <endpoint>https://storage.googleapis.com/{{ .Values.backup.gcsBucket }}/{{ .Values.backup.gcsPath }}/</endpoint>
            <access_key_id from_env="ACCESS_KEY_ID"/>
            <secret_access_key from_env="SECRET_ACCESS_KEY"/>
            <support_batch_delete>false</support_batch_delete>
          </backups>
        </disks>
        <policies>
          <backups_policy>
            <volumes>
              <main>
                <disk>backups</disk>
              </main>
            </volumes>
          </backups_policy>
        </policies>
      </storage_configuration>
      <backups>
        <allowed_disk>backups</allowed_disk>
        <!-- optional: <allowed_path>/</allowed_path> -->
      </backups>

    </clickhouse>
{{- end }}
