apiVersion: v1
kind: Pod
metadata:
  name: analytics
  namespace:  {{ .Values.namespace }} 
spec:
  serviceAccountName: analytics-sa
  containers:
  - name: analytics
    image: europe-west1-docker.pkg.dev/brain-staging-450115/clickhouse-analytics/clickhouse-analytics:latest
    command: ["sleep", "3600"]
    env:
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-clickhouse-secret 
            key: password             
      - name: CLICKHOUSE_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-clickhouse-secret 
            key: username    
      - name: CLICKHOUSE_SERVICE_NAME
        valueFrom:
          secretKeyRef:
            name: my-clickhouse-secret 
            key:  service_name
  restartPolicy: Never