apiVersion: v2
name: infomineo-langfuse
version: 1.0.3
description: Open source LLM engineering platform - LLM observability, metrics, evaluations, prompt management.
type: application
keywords:
  - langfuse
  - llm
  - observability
  - prompt management
  - metrics
dependencies:
  - name: clickhouse
    version: 9.0.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: clickhouse.deploy
  # - name: valkey
  #   version: 2.2.4
  #   repository: oci://registry-1.docker.io/bitnamicharts
  #   condition: redis.deploy
  #   alias: redis
  - name: common
    version: 2.31.4
    repository: oci://registry-1.docker.io/bitnamicharts
maintainers:
  - name: infomineo
    email: hazem.hany@infomineo.com
    url: https://infomineo.com/
appVersion: "1.0.0"
