apiVersion: batch/v1
kind: CronJob
metadata:
  name: analytics
  namespace: chatbot
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: analytics-sa
          containers:
          - name: analytics
            image: europe-west1-docker.pkg.dev/brain-prod-450115/clickhouse-analytics/clickhouse-analytics:latest
            # Launch a shell, then run the pipeline
            command: ["/bin/sh", "-c"]
            args:
              - >
                clickhouse-client \
                  --host "$CLICKHOUSE_SERVICE_NAME" \
                  --user "$CLICKHOUSE_USERNAME" \
                  --password "$CLICKHOUSE_PASSWORD" \
                  --query "SELECT id, name, timestamp, user_id, tags, session_id FROM default.traces WHERE timestamp >= now() - INTERVAL 1 DAY ORDER BY timestamp DESC FORMAT CSVWithNames" \
                | gsutil cp - gs://brain-langfuse-monitor-prod/batch/$(date +%Y-%m-%d)-table-extract.csv
            env:
              - name: CLICKHOUSE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: my-clickhouse-secret
                    key: password
              - name: CLICKHOUSE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: my-clickhouse-secret
                    key: username
              - name: CLICKHOUSE_SERVICE_NAME
                valueFrom:
                  secretKeyRef:
                    name: my-clickhouse-secret
                    key: service_name
          restartPolicy: OnFailure
