apiVersion: batch/v1
kind: CronJob
metadata:
  name: analytics-monthly-archive
  namespace: chatbot
spec:
  # Schedule: Run at 00:00 on the 1st day of every month.
  # You could also use the shorthand "@monthly"
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: analytics-sa
          containers:
          - name: analytics-monthly
            image: europe-west1-docker.pkg.dev/brain-prod-450115/clickhouse-analytics/clickhouse-analytics:latest
            # Launch a shell, then run the pipeline
            command: ["/bin/sh", "-c"]
            args:
              - >
                clickhouse-client \
                  --host "$CLICKHOUSE_SERVICE_NAME" \
                  --user "$CLICKHOUSE_USERNAME" \
                  --password "$CLICKHOUSE_PASSWORD" \
                  --query "SELECT id, name, timestamp, user_id, tags, session_id FROM default.traces WHERE timestamp >= now() - INTERVAL 2 MONTH ORDER BY timestamp DESC FORMAT CSVWithNames" \
                | gsutil cp - gs://brain-langfuse-monitor-prod/batch/monthly/$(date +%Y-%m)-monthly-archive.csv
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-clickhouse-secret
                  key: password
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-clickhouse-secret
                  key: username
            - name: CLICKHOUSE_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: my-clickhouse-secret
                  key: service_name
          restartPolicy: OnFailure