{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-backup
  namespace: chatbot

spec:
  # Weekly at midnight saturday 
  schedule: "0 0 * * 6"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: clickhouse-backup
              image: alexakulov/clickhouse-backup:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - >
                  apk add --no-cache gettext && \
                  envsubst < /etc/clickhouse-backup/config.yml > /etc/clickhouse-backup/config.rendered.yml &&
                  clickhouse-backup --config /etc/clickhouse-backup/config.rendered.yml create_remote weekly-$(date +%Y%m%d-%H%M)
              env:
                - name: CLICKHOUSE_HOST
                  value: {{ .Values.clickhouse.fullnameOverride }}
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: CLICKHOUSE_USER
                  valueFrom:
                    secretKeyRef:
                      name: my-clickhouse-secret
                      key: username
                - name: CLICKHOUSE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: my-clickhouse-secret
                      key: password
              volumeMounts:
                - name: gcs-credentials
                  mountPath: /etc/clickhouse-backup/backup-sa-key.json
                  subPath: backup-sa-key.json
                  readOnly: true
                - name: backup-config
                  mountPath: /etc/clickhouse-backup/config.yml
                  subPath: config.yml
          volumes:
            - name: gcs-credentials
              secret:
                secretName: clickhouse-backup-sa-secret
            - name: backup-config
              configMap:
                name: {{ .Values.clickhouse.fullnameOverride }}-backup-config

{{- end }}
