# templates/backup-cronjob.yaml
{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-backup
  namespace: {{ .Values.namespace }}
spec:
  # Weekly at midnight Saturday
  schedule: "0 0 * * 6"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          # Use the ServiceAccount we created above
          serviceAccountName: {{ .Values.clickhouse.fullnameOverride }}-backup-sa
          restartPolicy: OnFailure
          containers:
          - name: clickhouse-backup-trigger
            # An image that includes kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
            - |
              echo "Triggering ClickHouse backup in pod {{ .Values.clickhouse.fullnameOverride }}-shard0-0..."
              kubectl exec "{{ .Values.clickhouse.fullnameOverride }}-shard0-0" \
                --namespace {{ .Values.namespace }} \
                -c clickhouse-backup -- /bin/sh -c \
                'clickhouse-backup --config /tmp/config.yml create_remote weekly-$(date +%Y%m%d-%H%M)'
              echo "Backup trigger command finished."
{{- end }}