apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-backup-debug
  namespace: chatbot
spec:
  restartPolicy: Never
  containers:
    - name: clickhouse-backup
      image: alexakulov/clickhouse-backup:latest
      command: ["/bin/sh", "-c"]
      args: ["sleep infinity"]
      env:
        - name: CLICKHOUSE_HOST
          value: {{ .Values.clickhouse.fullnameOverride }} 
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: my-clickhouse-secret
              key: username
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-clickhouse-secret
              key: password
      volumeMounts:
        - name: gcs-credentials
          mountPath: /etc/clickhouse-backup/backup-sa-key.json
          subPath: backup-sa-key.json
          readOnly: true
        - name: backup-config
          mountPath: /etc/clickhouse-backup/config.yml
          subPath: config.yml
  volumes:
    - name: gcs-credentials
      secret:
        secretName: clickhouse-backup-sa-secret
    - name: backup-config
      configMap:
        name: {{ .Values.clickhouse.fullnameOverride }}-backup-config
