apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.langfuse.additionalEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: my-clickhouse-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.clickhouse.auth.username  | b64enc | quote }}
  password: {{ .Values.clickhouse.auth.password  | b64enc | quote }}
  service_name: {{ .Values.clickhouse.fullnameOverride  | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: bucket-access-key
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # The key must be CLICKHOUSE_PASSWORD for the official image to recognize it
  ACCESS_KEY_ID: {{ .Values.clickhouse.auth.access_key_id  | b64enc | quote }}
  SECRET_ACCESS_KEY: {{ .Values.clickhouse.auth.secret_access_key  | b64enc | quote }}