apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.langfuse.additionalEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: my-clickhouse-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.clickhouse.auth.username  | b64enc | quote }}
  password: {{ .Values.clickhouse.auth.password  | b64enc | quote }}
  backup_username: {{ .Values.clickhouse.auth.backup_username  | b64enc | quote }}
  backup_password: {{ .Values.clickhouse.auth.backup_password  | b64enc | quote }}
  service_name: {{ .Values.clickhouse.fullnameOverride  | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-backup-user
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  backup.xml: |
    <?xml version="1.0"?>
    <yandex>
      <users>
        <backupuser>
          <password>{{ .Values.clickhouse.auth.backup_password }}</password>
          <profile>default</profile>
          <networks>
            <ip>::/0</ip>
          </networks>
          <quota>default</quota>
        </backupuser>
      </users>
    </yandex>