apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.langfuse.additionalEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}