apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.langfuse.additionalEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: my-clickhouse-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.clickhouse.auth.username  | b64enc | quote }}
  password: {{ .Values.clickhouse.auth.password  | b64enc | quote }}
  backup_username: {{ .Values.clickhouse.auth.backup_username  | b64enc | quote }}
  backup_password: {{ .Values.clickhouse.auth.backup_password  | b64enc | quote }}
  service_name: {{ .Values.clickhouse.fullnameOverride  | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-backup-user
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  backup.xml: |
    {{- printf "<?xml version=\"1.0\"?>\n<yandex>\n  <users>\n    <backupuser>\n      <password>%s</password>\n      <profile>default</profile>\n      <networks>\n        <ip>::/0</ip>\n      </networks>\n      <allow_databases>\n        <database>*</database>\n      </allow_databases>\n      <grants>\n        <query>GRANT ALTER ON *.*</query>\n        <query>GRANT SELECT ON *.*</query>\n        <query>GRANT INSERT ON *.*</query>\n        <query>GRANT CREATE ON *.*</query>\n        <query>GRANT DROP ON *.*</query>\n      </grants>\n    </backupuser>\n  </users>\n</yandex>\n" .Values.clickhouse.auth.backup_password | b64enc | nindent 4 }}
