apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clickhouse.fullnameOverride }}-mysql-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: mysql-ssl
      port: 9005
      targetPort: 9005
      protocol: TCP
  selector:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: dashboard
    app.kubernetes.io/name: dashboard-clickhouse