apiVersion: v1
kind: Service
metadata:
  name: dashboard-worker-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dashboard-worker
  ports:
    - protocol: TCP
      port: {{ .Values.services.dashboardWorker.port }}
      targetPort: {{ .Values.services.dashboardWorker.targetPort }}
  type: {{ .Values.services.dashboardWorker.type }}
