{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: analytics
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
{{- end }}
