name: Staging - Build and Publish Langfuse web Docker Images

on:
  push:
    branches:
      - dev
    paths:
      - 'web/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 9.5.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set NEXT_PUBLIC_BUILD_ID
        run: echo "NEXT_PUBLIC_BUILD_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Echo Commit Hash
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "Building commit hash: $COMMIT_HASH"
      
      # authenticate to GCP artifact registry
      - name: GCP Authenticate Github
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.STAGE_GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate Docker to GCP Artifact registry
        run: gcloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev"
      
      # setup docker builder environment
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      # build web
      - name: Build and push Docker image (web)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.STAGE_GCP_PROJECT_ID }}/brain-langfuse-web/langfuse:latest
          labels: ${{ steps.meta-web.outputs.labels }}
          platforms: linux/amd64
          provenance: false
          sbom: false
